{% set version = "0.37" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bestglm
  version: {{ version|replace("-", "_") }}

source:
  fn: bestglm_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/bestglm_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/bestglm/bestglm_{{ version }}.tar.gz
  sha256: 9f268572dea45b9da5850a8e7d5a88628462344281ef3ced15f8d5721e89103e

build:
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-glmnet
    - r-grpreg
    - r-lattice
    - r-leaps
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - r-glmnet
    - r-grpreg
    - r-lattice
    - r-leaps
    - libgcc  # [not win]

test:
  commands:
    - $R -e "library('bestglm')"  # [not win]
    - "\"%R%\" -e \"library('bestglm')\""  # [win]

about:
  home: http://www.stats.uwo.ca/faculty/aim
  license: GPL (>= 2)
  summary: Best subset glm using information criteria or cross-validation.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
