{% set version = "0.37.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bestglm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/bestglm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/bestglm/bestglm_{{ version }}.tar.gz
  sha256: ca038764c9393a1955456e3666f2cafe56836d0c787b7373f79e53884af2ccfe

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-glmnet
    - r-grpreg
    - r-lattice
    - r-leaps
    - r-pls
  run:
    - r-base
    - r-glmnet
    - r-grpreg
    - r-lattice
    - r-leaps
    - r-pls

test:
  commands:
    - $R -e "library('bestglm')"           # [not win]
    - "\"%R%\" -e \"library('bestglm')\""  # [win]

about:
  home: http://www.stats.uwo.ca/faculty/aim
  license: GPL (>= 2)
  summary: Best subset glm using information criteria or cross-validation. Implements PCR and PLS using AIC/BIC. Implements one-standard deviation rule for use with
    the `caret` package.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: bestglm
# Type: Package
# Title: Best Subset GLM and Regression Utilities
# Version: 0.37
# Date: 2018-05-27
# Author: A.I. McLeod  and Changjiang Xu
# Maintainer: A.I. McLeod <aimcleod@uwo.ca>
# Depends: R (>= 2.0.0), leaps
# Suggests: MASS
# Imports: lattice, glmnet, grpreg, pls
# Enhances: caret
# Description: Best subset glm using information criteria or cross-validation. Implements PCR and PLS using AIC/BIC. Implements one-standard deviation rule for use with the `caret` package.
# LazyLoad: yes
# LazyData: yes
# Classification/ACM: G.3, G.4, I.5.1
# Classification/MSC: 62M10, 91B84
# License: GPL (>= 2)
# URL: http://www.stats.uwo.ca/faculty/aim
# NeedsCompilation: yes
# Packaged: 2018-05-27 19:27:22 UTC; IanMcLeod
# Repository: CRAN
# Date/Publication: 2018-05-27 21:03:04 UTC
